### ISSUE TITLE
Invalid models with Pydantic 2

### ISSUE THREAD

**Issue by matteocacciolamotork** [jtom38/fastapi_healthcheck#32]
Optional attributes in Models, like [totalTimeTaken](https://github.com/jtom38/fastapi_healthcheck/blob/master/fastapi_healthcheck/model.py#L17), should have a default value when used in some places like [self._health = HealthCheckModel()]https://github.com/jtom38/fastapi_healthcheck/blob/master/fastapi_healthcheck/service.py#L50, otherwise Pydantic 2 provides errors

**Comment by onlinejudge95** [comment]
+1 receiving the following error when using the example as mentioned in the repo. @jtom38 

```
backend-server-1  | INFO:     172.18.0.1:45532 - "GET /api/health HTTP/1.1" 500 Internal Server Error
backend-server-1  | ERROR:    Exception in ASGI application
backend-server-1  | Traceback (most recent call last):
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
backend-server-1  |     result = await app(  # type: ignore[func-returns-value]
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
backend-server-1  |     return await self.app(scope, receive, send)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
backend-server-1  |     await super().__call__(scope, receive, send)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
backend-server-1  |     await self.middleware_stack(scope, receive, send)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-server-1  |     raise exc
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-server-1  |     await self.app(scope, receive, _send)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-server-1  |     raise exc
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-server-1  |     await self.app(scope, receive, sender)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
backend-server-1  |     raise e
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
backend-server-1  |     await self.app(scope, receive, send)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
backend-server-1  |     await route.handle(scope, receive, send)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
backend-server-1  |     await self.app(scope, receive, send)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
backend-server-1  |     response = await func(request)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
backend-server-1  |     raw_response = await run_endpoint_function(
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
backend-server-1  |     return await run_in_threadpool(dependant.call, **values)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
backend-server-1  |     return await anyio.to_thread.run_sync(func, *args)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
backend-server-1  |     return await get_asynclib().run_sync_in_worker_thread(
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
backend-server-1  |     return await future
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
backend-server-1  |     result = context.run(func, *args)
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi_healthcheck/route.py", line 18, in endpoint
backend-server-1  |     res = _factory.check()
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi_healthcheck/service.py", line 50, in check
backend-server-1  |     self._health = HealthCheckModel()
backend-server-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
backend-server-1  |     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
backend-server-1  | pydantic_core._pydantic_core.ValidationError: 1 validation error for HealthCheckModel
backend-server-1  | totalTimeTaken
backend-server-1  |   Field required [type=missing, input_value={}, input_type=dict]
backend-server-1  |     For further information visit https://errors.pydantic.dev/2.4/v/missing
```
